version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datastore
    ports:
      - "3306:3306"

volumes:
  db: